replicaCount: 3
mage:
  repository: us-central1-docker.pkg.dev/terraform-project-islom/artemis/artemis
  pullPolicy: IfNotPresent
  tag: "2.0.0"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations:     
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: qa-artemis.omahaaws.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  # - secretName: qa-artemis-tls
  #   hosts:
  #     - qa-artemis.omahaaws.net
